### PR TITLE
fix: add Algolia logo

### PR DESCRIPTION
**Pull request by Haroenv**
This is required under our usage of the npm-search index, so that other people can find out how to use it too

### CODE REVIEW

**Comment by ryan-roemer** [comment]
Hi @Haroenv !

Thanks for your collection of PRs! We weren't aware of required terms for use of Algolia, but we're happy to add the logo for the lovely search you're providing.

So that we can track this better, would you mind adding a few code comments here https://github.com/FormidableLabs/runpkg/blob/e497632a6db753322be4422731d9d791408a42e0/utils/rplus.js#L8 where we instantiate the Algolia client to link to the service we're using and the terms of service for use?

As someone, who just took a look around, and wasn't familiar with the code it would be a great maintainability improvement for all developers to just see what we're using and under what terms.

Thanks!

**Comment by Haroenv** [comment]
Sounds good! I’ll add a link tomorrow

**Comment by Haroenv** [comment]
added this link @ryan-roemer :) https://www.algolia.com/doc/faq/accounts-billing/do-i-need-to-display-the-algolia-logo-when-i-am-on-the-free-plan/

**Review by ryan-roemer — APPROVED** [review]

**Comment by Haroenv** [comment]
thanks for merging @ryan-roemer !

**Pull request merged**
