### PR TITLE
Add Not found state - Fix issue #190

### PR DESCRIPTION
**Pull request by Zerelt**
Fix issue #190

Adds a check on the Main.js file if the response is not ok and there is no file version, we make use of the new reducer state and display the not found message which re-uses the same components/styling as the original Article content. At the same time we directly display the Registry list for a better UX, so the user doesn't have to figure out he/she needs to go there.

Without the `&& request.version` part we'd run into other issues with the caching/history because some search results respond with a 404 but they're still present in the registry ( re-act or reast for example ). Clicking one of these would show the "not found" message but if you then go back it would display files.

### CODE REVIEW

**Comment by andyrichardson** [comment]
Kapture 2021-02-22 at 12 36 27

Just tested it out - looks good!

I think it would be cool to swap out the logo for some kind of exclamation mark or something to draw attention to that area of the app.

That being said, I'm happy merging this as-is!

@at-syot as you expressed some interest in this, do you want to give it a quick review and any feedback?

**Comment by lukejacksonn** [comment]
Yeh, awesome work.. I also think an exclamation mark like you suggest @andyrichardson would work great here!

**Review by andyrichardson — APPROVED** [review]
Awesome work!

**Comment by Zerelt** [comment]
Added a new icon I made in Adobe XD. Let me know if that works for you guys or if had something different in mind. @andyrichardson @lukejacksonn

**Review by at-syot — APPROVED** [review]
Look good ^^

**Comment by andyrichardson** [comment]
Awesome work! Merging this!

**Pull request merged**
